version: '3.8'

networks:
  shared-network:
    driver: bridge

services:
  db:
    container_name: people-postgres-dev
    networks:
      - shared-network
    image: postgres:latest
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - "5435:5435"
    volumes:
      - $PWD/data/postgres-dev:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=12345
      - POSTGRES_USER=postgres
      - POSTGRES_DB=people

  people:
    container_name: people
    networks:
      - shared-network
    image: 730335383193.dkr.ecr.eu-north-1.amazonaws.com/people:latest
    command: --spring.datasource.url=jdbc:postgresql://db:5435/people --spring.profiles.active=dev --logging.level.root=info --server.port=8080
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy